import './globals.css'
import Header from '@/views/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className='w-full min-h-screen px-4 py-8 bg-zinc-400 '>
        {children}
        
        </main></body>
    </html>
  )
}
